// Select all the elements we need
const form = document.getElementById('qrForm');
const urlInput = document.getElementById('urlInput');
const qrcodeContainer = document.getElementById('qrcode-container');
const downloadBtn = document.getElementById('downloadBtn');

// Handle form submission
form.addEventListener('submit', function(e) {
    e.preventDefault(); // Stop the form from reloading the page
    
    const url = urlInput.value.trim();
    if (!url) return; // Don't do anything if the input is empty

    // Clear previous QR code and show loading
    qrcodeContainer.innerHTML = '<p>Generating...</p>';
    downloadBtn.hidden = true; // Hide download button

    // Generate the QR code as a canvas
    QRCode.toCanvas(url, { width: 200, margin: 2 }, function (error, canvas) {
        qrcodeContainer.innerHTML = ''; // Clear "Generating..."
        if (error) {
            console.error(error);
            qrcodeContainer.textContent = 'Error generating QR code.';
        } else {
            // Success! Append the canvas to the div
            qrcodeContainer.appendChild(canvas);
            // Show the download button
            downloadBtn.hidden = false;
        }
    });
});

// Handle download button click
downloadBtn.addEventListener('click', function() {
    // Find the canvas element generated by the library
    const canvas = qrcodeContainer.querySelector('canvas');
    if (!canvas) return;

    // Create an "a" element to trigger the download
    const link = document.createElement('a');
    // Convert canvas to a PNG image data URL
    link.href = canvas.toDataURL('image/png');
    // Set the filename for the download
    link.download = 'qrcode.png';
    // Trigger the download
    link.click();
});

// Bonus: Reset the UI if the user starts typing again
urlInput.addEventListener('input', function() {
    downloadBtn.hidden = true;
    qrcodeContainer.innerHTML = '<p>Your QR code will appear here</p>';
});